config/routes.rb
Rails.application.routes.draw do
  get 'privacy_policy', to: 'privacy_policy#index'
  get 'welcome/index'
  root 'welcome#index'
  resources :events do
    member do
      post '/invite', to: 'events#invite_user'
    end
  end
  resources :users do
    member do
      post '/accept_invite', to: 'users#accept_invite'
      post '/going', to: 'users#mark_going'
      post '/gcal', to: 'users#add_to_gcal'
    end
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#google_auth'
  get 'auth/failure', to: redirect('/')
end

app/models/user.rb
class User < ApplicationRecord
  include BCrypt
  before_destroy :destroy_owned_events

  validates_presence_of :first_name, :last_name, :email
  validates_uniqueness_of :email
  validate :first_name_must_be_capitalized
  validate :last_name_must_be_capitalized
  validate :email_must_have_at_and_dot

  has_many :events_users, dependent: :destroy
  has_many :events, through: :events_users, source: :event
  has_many :invites_received, class_name: 'Invite', foreign_key: 'invitee_id', dependent: :destroy
  has_many :invites_sent, class_name: 'Invite', foreign_key: 'inviter_id', dependent: :destroy

  def destroy_owned_events
    events_hosting.each(&:destroy)
  end

  def events_hosting
    created = []
    events.order(date: :desc).each do |event|
      created << event if event.creator == self
    end
    created
  end

  def events_attending
    attending = []
    events.order(date: :desc).each do |event|
      attending << event if event.creator != self
    end
    attending
  end

  def accept_invite(event)
    invite = Invite.find_by(invitee: self, event: event)
    return if invite.nil?

    event.attendees << self
    invite.destroy
  end

  def first_name_must_be_capitalized
    errors.add(:first_name, 'must be capitalized') if first_name && first_name[0, 1] != first_name[0, 1].upcase
  end

  def last_name_must_be_capitalized
    errors.add(:last_name, 'must be capitalized') if last_name && last_name[0, 1] != last_name[0, 1].upcase
  end

  def email_must_have_at_and_dot
    errors.add(:email, "must have an '@' and a '.'") if email && (!email.include?('@') || !email.include?('.'))
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def password
    @password ||= Password.new(password_hash) unless password_hash.nil?
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index, :new, :create]
  before_action :authenticate_user, except: [:index, :show, :new, :create]

  Calendar = ::Google::Apis::CalendarV3
  Client = ::Signet::OAuth2::Client

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    return if @user == current_user

    redirect_back fallback_location: root_path, error: 'You can only edit your own account.'
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user == current_user
      if @user.update(user_params)
        session[:user_id] = @user.id
        redirect_to @user, notice: "#{@user.full_name} was successfully updated."
      else
        render :edit
      end
    else
      redirect_to @user, error: 'You can only update your own account.'
    end
  end

  # DELETE /users/1
  def destroy
    if @user == current_user
      reset_session
      name = @user.full_name
      @user.destroy
      redirect_to users_url, notice: "#{name} was successfully destroyed."
    else
      redirect_to users_url, error: 'You can only destroy your own account.'
    end
  end

  # POST /users/1/accept_invite
  def accept_invite
    if @user == current_user
      event = Event.find(params[:event_id])
      @user.accept_invite(event)
      redirect_back fallback_location: @user, notice: "Successfully accepted invite to #{event.title}."
    else
      redirect_to users_url, error: 'You can only accept invites you received.'
    end
  end

  # POST /users/1/going
  def mark_going
    event = Event.find(params[:event_id])
    @user.events << event
    redirect_back fallback_location: @user, notice: "Marked going to #{event.title}."
  end

  # POST /users/1/gcal
  def add_to_gcal
    service = Calendar::CalendarService.new
    # Use google keys to authorize
    service.authorization = credentials

    # Request for a new access token just in case it expired
    service.authorization.refresh!

    event = Event.find(params[:event_id])

    gcal_event = Google::Apis::CalendarV3::Event.new(
      start: Google::Apis::CalendarV3::EventDateTime.new(date_time: event.date.rfc3339),
      end: Google::Apis::CalendarV3::EventDateTime.new(date_time: (event.date + 1.hours).rfc3339),
      summary: event.title,
      description: event.description,
      location: event.location
    )

    service.insert_event('primary', gcal_event)
    redirect_back fallback_location: @user, notice: "Added #{event.title} to calendar."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

  def credentials
    Client.new(
      access_token: @user.google_token,
      refresh_token: @user.google_refresh_token,
      client_id: Rails.application.secrets.google_client_id,
      client_secret: Rails.application.secrets.google_client_secret,
      scope: ['userinfo.email', 'userinfo.profile', Calendar::AUTH_CALENDAR_EVENTS],
      redirect_uri: OmniAuth.config.full_host + '/auth/google_oauth2/callback',
      authorization_uri: 'https://accounts.google.com/o/oauth2/auth',
      token_credential_uri: 'https://oauth2.googleapis.com/token'
    )
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <h6><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h6>

      <ul style="margin-bottom: 0px;">
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      <button type="button" class="close" data-dismiss='alert' aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>
<br>
<%= link_to 'Back', :back, class: 'btn btn-secondary' %>

app/views/users/index.html.erb
<div class="row">
  <div class="col">
    <div class="row">
      <div class="col">
        <h1 style="text-align: center">Users</h1>
      </div>
    </div>
    <% if @users.empty? %>
      <div class="row">
        <div class="col">
          <h6 style="text-align: center">There are no users yet. <%= link_to 'Why not make an account?', new_user_path %></h6>
        </div>
      </div>
    <% else %>
      <% if logged_in? %>
        <div class="row"><h4>Your account:</h4></div>
        <div class="row" style="margin-top: 5px; margin-bottom: 5px">
          <div class="col card">
            <div class="card-body" id=<%= "user_#{current_user.id}" %>>
              <div class="row">
                <h5 class="card-title"><%= link_to current_user.full_name, current_user %></h5>
              </div>
              <div class="row"><%= current_user.email %></div>
              <div class="row" style="margin-top: 10px;">
                <%= link_to 'Edit account', edit_user_path(current_user), class: 'btn btn-secondary' %>&nbsp;
                <%= link_to 'Delete account', current_user, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
              </div>
            </div>
          </div>
        </div>
        <div class="row"><h4>Other accounts:</h4></div>
      <% end %>
      <% (@users - [current_user]).each do |user| %>
        <div class="row" style="margin-top: 5px; margin-bottom: 5px">
          <div class="col card">
            <div class="card-body" id=<%= "user_#{user.id}" %>>
              <div class="row">
                <h5 class="card-title"><%= link_to user.full_name, user %></h5>
              </div>
              <div class="row"><%= user.email %></div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>
<br>
<h4>Already have an account? <%= link_to 'Log in.', '/login' %></h4>

app/views/users/show.html.erb
<div class="row">
  <div class="col">
    <div class="row"><h1><%= @user.full_name %></h1></div>
    <div class="row" style="margin-top: 5px;">
      <div class="col card">
        <div class="card-body">
          <h6 style="margin-top: 8px;">Email: <%= mail_to @user.email %></h6>
          <% if current_user == @user %>
            <%= link_to 'Edit account', edit_user_path(current_user), class: 'btn btn-secondary' %>&nbsp;
            <%= link_to 'Delete account', current_user, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
            <% if current_user.google_token.nil? %>
              <br><%= link_to 'Connect account to Google Calendar', '/auth/google_oauth2', class: 'btn btn-success', style: 'margin-bottom: 5px; margin-top: 5px' %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row" style="margin-top: 5px;">
      <div class="col card">
        <div class="card-body" id="events-created">
          <h6>Events Created:</h6>
          <ul style="margin-bottom: 0px">
            <% if @user.events_hosting.empty? %>
              <% if current_user == @user %>
                <li>You have not created any events. <%= link_to "Make one?", new_event_path %></li>
              <% else %>
                <li><%= @user.first_name %> is not hosting any events.</li>
              <% end %>
            <% else %>   
              <% @user.events_hosting.each do |event| %>
                <li><%= link_to event.title, event %></li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="row" style="margin-top: 5px;">
      <div class="col card">
        <div class="card-body" id="events-attending">
          <h6>Events Attending:</h6>
          <ul style="margin-bottom: 0px">
            <% if @user.events_attending.empty? %>
              <% if current_user == @user %>
                <li>You are not attending any events you didn't create. <%= link_to "Mark 'Going' to one?", events_path %></li>
              <% else %>
                <li><%= @user.first_name %> is not attending any events they didn't create. <%= link_to "Invite them to an event?", events_path %></li>
              <% end %>
            <% else %>
              <% @user.events_attending.each do |event| %>
                <li><%= link_to event.title, event %></li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="row" style="margin-top: 5px;">
      <div class="col card">
        <div class="card-body" id="invites-pending">
          <h6>Invites Pending:</h6>
          <ul style="margin-bottom: 0px">
            <% if @user.invites_received.empty? %>
              <% if current_user == @user %>
                <li>You have no invites yet. <%= link_to 'Ask a friend to invite you to an event?', users_path %></li>
              <% else %>
                <li><%= @user.first_name %> has not been invited to any events. <%= link_to "Invite them to an event?", events_path %></li>
              <% end %>
            <% else %>
              <% @user.invites_received.each do |invite| %>
                <% if current_user == @user %>
                  <li>
                    <%= link_to invite.inviter.full_name, invite.inviter %> invited you to <%= link_to invite.event.title, invite.event %>. <%= button_to 'Accept Invite', accept_invite_user_path(@user.id), params: { event_id: invite.event.id }, class: 'btn btn-sm btn-success' %>
                  </li>
                <% else %>
                  <li><%= link_to invite.inviter.full_name, invite.inviter %> invited <%= @user.first_name %> to <%= link_to invite.event.title, invite.event %></li>
                <% end %>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>