config/routes.rb
Rails.application.routes.draw do
  get 'privacy_policy', to: 'privacy_policy#index'
  get 'welcome/index'
  root 'welcome#index'
  resources :events do
    member do
      post '/invite', to: 'events#invite_user'
    end
  end
  resources :users do
    member do
      post '/accept_invite', to: 'users#accept_invite'
      post '/going', to: 'users#mark_going'
      post '/gcal', to: 'users#add_to_gcal'
    end
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#google_auth'
  get 'auth/failure', to: redirect('/')
end

app/models/event.rb
class Event < ApplicationRecord
  validates_presence_of :title, :description, :location, :date
  validates_uniqueness_of :title
  belongs_to :creator, class_name: 'User'
  has_many :events_users, dependent: :destroy
  has_many :attendees, through: :events_users, source: :user
  has_many :invites, dependent: :destroy

  def invitees
    invites.map(&:invitee)
  end

  def invite_user(inviter, invitee)
    return false if Invite.exists?(invitee: invitee, event: self) || attendees.include?(invitee)

    invite = Invite.new(inviter: inviter, invitee: invitee, event: self)
    inviter.invites_sent << invite
    invitee.invites_received << invite
    invite.save
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :invite_user]
  before_action :authenticate_user, only: [:new, :create, :edit, :update, :destroy, :invite_user]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
    @users = User.all
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    return if @event.creator == current_user

    redirect_back fallback_location: root_path, error: 'You can only edit an event you created.'
  end

  # POST /events
  def create
    @event = Event.new(event_params)
    @event.creator = current_user
    @event.attendees << current_user
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if current_user == @event.creator
      if @event.update(event_params)
        redirect_to @event, notice: 'Event was successfully updated.'
      else
        render :edit
      end
    else
      redirect_to @event, error: 'You can only update an event you created.'
    end
  end

  # DELETE /events/1
  def destroy
    if current_user == @event.creator
      @event.destroy
      redirect_to events_url, notice: 'Event was successfully destroyed.'
    else
      redirect_to @event, notice: 'You can only delete an event you created.'
    end
  end

  # POST events/1/invite
  def invite_user
    inviter = User.find(session[:user_id])
    invitee = User.find(params[:user_id])
    if @event.invite_user(inviter, invitee)
      redirect_back fallback_location: @event, notice: 'User was successfully invited.'
    else
      redirect_back fallback_location: @event, error: 'An error happened while inviting the user'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :description, :location, :date)
  end
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <h6><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h6>

      <ul style="margin-bottom: 0px;">
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
      <button type="button" class="close" data-dismiss='alert' aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :event_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :event_description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location, id: :event_location, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.datetime_field :date, order: [:month, :day, :year, :hour, :minute], ampm: true, id: :event_date, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>
<br>
<%= link_to 'Back', 'back', class: 'btn btn-secondary' %>

app/views/events/index.html.erb
<div class="row">
  <div class="col">
    <div class="row">
      <div class="col">
        <h1 style="text-align: center">Events</h1>
      </div>
    </div>
    <% if logged_in? %>
    <div class="row"><h4>Your events:</h4></div>
      <% if current_user.events_hosting.empty? %>
      <div class="row"><h6>You haven't made any events yet. <%= link_to 'Why not make one?', '/events/new' %></h6></div>
      <% else %>
        <% current_user.events_hosting.each do |event| %>
          <div class="row" style="margin-top: 5px; margin-bottom: 5px;">
            <div class="col card">
              <div class="card-body" id=<%= "event_#{event.id}" %>>
                <h4 class="card-title"><%= link_to event.title, event %></h4>
                <p class="card-text">
                  <%= event.description %>
                </p>
                <h6>Location: <%= event.location %></h6>
                <h6>Date: <%= event.date.strftime("%B %d, %Y") %></h6>
                <h6>Time: <%= event.date.strftime("%l:%M %P") %></h6>
                <h6>Creator: <%= link_to event.creator.full_name, event.creator %></h6>
                <%= link_to 'Edit event', edit_event_path(event), class: 'btn btn-secondary' %>
                <%= link_to 'Delete event', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                <% if current_user.google_token.present? %>
                  <br>
                  <%= button_to 'Add to calendar', gcal_user_path(current_user.id), params: { event_id: event.id }, class: 'btn btn-success', style: 'margin-top: 5px;' %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <div class="row"><h4>Other events:</h4></div>
      <% if (@events.order(:date) - current_user.events_hosting).empty? %>
        <div class="row"><h6>There are no other events yet. Tell another user to make one!</h6></div>
      <% else %>
        <% (@events - current_user.events_hosting).each do |event| %>
          <div class="row" style="margin-top: 5px; margin-bottom: 5px;">
            <div class="col card">
              <div class="card-body" id=<%= "event_#{event.id}" %>>
                <h4 class="card-title"><%= link_to event.title, event %></h4>
                <p class="card-text">
                  <%= event.description %>
                </p>
                <h6>Location: <%= event.location %></h6>
                <h6>Date: <%= event.date.strftime("%B %d, %Y") %></h6>
                <h6>Time: <%= event.date.strftime("%l:%M %P") %></h6>
                <h6>Creator: <%= link_to event.creator.full_name, event.creator %></h6>
                <% if event.attendees.include?(current_user) %>
                  <button type="button" class="btn btn-success" style="margin-bottom: 5px;" disabled>Going</button>
                  <% if current_user.google_token.present? %>
                    <%= button_to 'Add to calendar', gcal_user_path(current_user.id), params: { event_id: event.id }, class: 'btn btn-success', style: 'margin-bottom: 5px;' %>
                  <% end %>
                <% elsif Invite.find_by(invitee: current_user, event: event) %>
                  <%= button_to 'Accept Invite', accept_invite_user_path(current_user.id), params: { event_id: event.id }, class: 'btn btn-success' %>
                <% else %>
                  <%= button_to 'Mark Going', going_user_path(current_user.id), params: { event_id: event.id }, class: 'btn btn-success' %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <% if @events.empty? %>
        <div class="row">
          <div class="col">
            <h6 style="text-align: center">There are no events yet. <%= link_to 'Why not sign up and make an event?', new_user_path %></h6>
          </div>
        </div>
      <% else %>
        <% @events.each do |event| %>
          <div class="row" style="margin-top: 5px; margin-bottom: 5px;">
            <div class="col card">
              <div class="card-body" id=<%= "event_#{event.id}" %>>
                <h4 class="card-title"><%= link_to event.title, event %></h4>
                <p class="card-text">
                  <%= event.description %>
                </p>
                <h6>Location: <%= event.location %></h6>
                <h6>Date: <%= event.date.strftime("%B %d, %Y") %></h6>
                <h6>Time: <%= event.date.strftime("%l:%M %P") %></h6>
                <h6>Creator: <%= link_to event.creator.full_name, event.creator %></h6>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>
<br>
<%= link_to 'Back', :back, class: 'btn btn-secondary' %>

app/views/events/show.html.erb
<div class="row">
  <div class="col">
    <div class="row"><h1><%= @event.title %></h1></div>
    <div class="row" style="margin-top: 5px;">
      <div class="col card">
        <div class="row card-body">
          <div class="col">
            <p class="card-text">
              <%= @event.description %>
            </p>
            <h6>Location: <%= @event.location %></h6>
            <h6>Date: <%= @event.date.strftime("%B %d, %Y") %></h6>
            <h6>Time: <%= @event.date.strftime("%l:%M %P") %></h6>
            <h6>Creator: <%= link_to @event.creator.full_name, @event.creator %></h6>
            <% if logged_in? %>
              <% if current_user == @event.creator %>
                <%= link_to 'Edit event', edit_event_path(@event), class: 'btn btn-sm btn-secondary' %>
                <%= link_to 'Delete event', @event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
                <% if current_user.google_token.present? %>
                  <%= button_to 'Add to calendar', gcal_user_path(current_user.id), params: { event_id: @event.id }, class: 'btn btn-sm btn-success', style: 'margin-top: 5px' %>
                <% end %>
              <% else %>
                <% if @event.attendees.include?(current_user) %>
                  <button type="button" class="btn btn-sm btn-success" style="margin-bottom: 5px;" disabled>Going</button>
                  <%= button_to 'Add to calendar', gcal_user_path(current_user.id), params: { event_id: @event.id }, class: 'btn btn-sm btn-success'%>
                <% elsif Invite.find_by(invitee: current_user, event: @event) %>
                  <%= button_to 'Accept Invite', accept_invite_user_path(current_user.id), params: { event_id: @event.id }, class: 'btn btn-sm btn-success' %>
                <% else %>
                  <%= button_to 'Mark Going', going_user_path(current_user.id), params: { event_id: @event.id }, class: 'btn btn-sm btn-success' %>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <div class="col">
            <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{@event.location}&zoom=14&size=300x300&markers=color:red%7C#{@event.location}&key=#{Rails.application.secrets.google_maps_api_key}", alt: "Map", style: 'float: right;' %>
          </div>
        </div>
      </div>
    </div>
    <div class="row" style="margin-top: 5px;">
      <div class="col card">
        <div class="card-body" id="event-attendees">
          <h6>People Going:</h6>
          <ul style="margin-bottom: 0px">
            <% @event.attendees.each do |attendee| %>
            <li><%= link_to attendee.full_name, attendee %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="row" style="margin-top: 5px;">
      <div class="col card">
        <div class="card-body" id="event-invitees">
          <h6>People Invited:</h6>
          <ul style="margin-bottom: 0px">
            <% if @event.invitees.empty? %>
              <li>Nobody has been invited to the event yet. Invite someone below!</li>
            <% else %>
              <% @event.invitees.each do |invitee| %>
              <li><%= link_to invitee.full_name, invitee %></li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="row" style="margin-top: 5px;">
      <div class="col card">
        <div class="card-body" id="invite-user">
          <h6>Invite User</h6>
          <%= form_with url: "/events/#{@event.id}/invite" do |form| %>
            <%= form.collection_select :user_id, @users - @event.attendees - @event.invitees - [current_user], :id, :full_name, {:include_blank => true}, {:class => 'form-control'} %>
            <%= form.submit 'Invite', class: 'btn btn-success btn-sm', style: 'margin-top: 10px;' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>